version: '3.6'

services:
  server:
    build: './server'
    ports:
      - "8000"
  nginx:
    build: "./nginx"
    ports:
      - target: 7000
        published: 7000
        mode: host
    depends_on:
      - server